//---------------------------------------------------------------------------
//   Arquivo de chave RSA 1024
//   Gravado em [C:\TQSAPP\QINLOCO\APLIC\QINLOCO\TQSProt\QINLOCO_EXE_CPU.H] em 21-09-2017 17:11:13
//   Pelo programa TQSASSIN.EXE
//   Chave pública correspondente ao arquivo [C:\TQSAPP\QINLOCO\APLIC\QINLOCO\TQSProt\QINLOCO.EXE]
//---------------------------------------------------------------------------
unit QINLOCO_EXE_CPU; 
interface
uses APLICTQS;
var
glb_chapubl: TChave = (
	$30, $81, $9D, $30, $0D, $06, $09, $2A, $86, $48, 
	$86, $F7, $0D, $01, $01, $01, $05, $00, $03, $81, 
	$8B, $00, $30, $81, $87, $02, $81, $81, $00, $B9, 
	$C8, $05, $15, $6B, $16, $36, $45, $15, $86, $0E, 
	$FB, $94, $73, $8F, $64, $ED, $56, $71, $D3, $FC, 
	$3C, $4F, $F5, $65, $D5, $E7, $FE, $C4, $2C, $3D, 
	$0F, $DA, $3F, $D3, $64, $8A, $C7, $49, $2E, $4E, 
	$D7, $F1, $64, $A8, $48, $CB, $5A, $2C, $D5, $9A, 
	$B3, $F3, $FD, $8C, $2E, $DE, $6A, $86, $19, $F0, 
	$EF, $43, $BD, $C1, $46, $AB, $94, $D7, $B8, $33, 
	$9E, $80, $34, $85, $6F, $BA, $B8, $5A, $F1, $C0, 
	$11, $39, $4F, $C9, $45, $0E, $27, $0C, $86, $5C, 
	$CE, $D6, $D5, $1B, $5A, $E4, $62, $73, $9F, $89, 
	$FF, $71, $B0, $AC, $D8, $7F, $D7, $7B, $62, $42, 
	$A4, $89, $BE, $E6, $BB, $44, $F7, $7E, $F6, $3B, 
	$1A, $1D, $C9, $D1, $D3, $C7, $57, $02, $01, $11  
    );
implementation
end.
